apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: static_site
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      app: static_site
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: static_site
        deployment: blue
    spec:
      containers:
      - image: ezeebube5/static_site:blue
        imagePullPolicy: Always
        name: static_site
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
      restartPolicy: Always