---
- name: Deploy
  hosts: [localhost]
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python2
  tasks:
    - name: Get facts for master
      ec2_instance_info:
        filters:
          "tag:Name": master
