---
- name: Deploy
  hosts: [localhost]
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python2
  tasks:
    - name: Ensure boto and boto3 modules are installed
      pip:
        name: ['boto3', 'botocore']
    
    - name: Get facts for master
      ec2_instance_info:
        region: us-east-2
        filters:
          "tag:Name": master
      register: ec2_master 

    - name: Print info
      debug: msg="{{ ec2_master['instances'][0]['private_ip_address'] }}"
    
    - name: Add instance private IPs to group
      add_host:
        hostname: master
        ansible_host: "{{ item.private_ip_address }}"
        groups: ec2master
      loop: "{{ ec2_master.instances[0] }}"
