---
- name: Deploy
  hosts: [localhost]
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python2
  tasks:
    - name: Ensure boto and boto3 modules are installed
      pip:
        name: ['boto3', 'botocore']
    
    - name: Get facts for master
      ec2_instance_info:
        region: us-east-2
        filters:
          "tag:Name": master
      register: master_info 

    - name: Print info
      debug: var={{ item.private_ip }}
      with_items: master_info.instances
