---
- name: Deploy
  hosts: [localhost]
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python2
  tasks:
    - name: Ensure boto and boto3 modules are installed
      pip:
        name: "{{ item }}"
      with_items:
        - boto3
        - botocore
    
    - name: Get facts for master
      ec2_instance_info:
        filters:
          "tag:Name": master
