apiVersion: v1
kind: Service
metadata:
  name: static_site
  namespace: default
spec:
  ports:
  - nodePort: 30007
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: static_site
    deployment: blue
  type: NodePort
status:
  loadBalancer: {}
