- name: Create EC2 instances for worker nodes
  ec2:
    key_name: pipeline
    instance_type: t2.large
    image: ami-0fc20dd1da406780b
    user_data: "{{ USERDATA }}"
    region: us-east-2
    group_id: sg-0cfe69542efa6f501
    wait: yes
    instance_tags:
      Name: worker
      application: "{{ application }}"
    exact_count: 2
    count_tag:
      application: "{{ application }}"
  register: ec2_worker

- name: Create EC2 instances for worker master
  ec2:
    key_name: pipeline
    instance_type: t2.large
    image: ami-0fc20dd1da406780b
    user_data: "{{ USERDATA }}"
    region: us-east-2
    group: sg-k8s-cluster
    wait: yes
    instance_tags:
      Name: master
      application: "{{ application }}"
    exact_count: 1
    count_tag:
      application: "{{ application }}"
  register: ec2_master  
